version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: app
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
  server:
    image: app
    command: npm run dev-server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - app